apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "titlis.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "titlis.fullname" . }}-clusterrole  # ← Usar novo nome
subjects:
  - kind: ServiceAccount
    name: {{ include "titlis.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}