{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "castai-monitor.fullname" . }}-datadog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-monitor.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: titlis-datadog-keys
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ .Values.externalSecret.datadogPath }}
        property: api_key
    - secretKey: app-key
      remoteRef:
        key: {{ .Values.externalSecret.datadogPath }}
        property: app_key
{{- end }}
